name: build_release_deploy


# Only trigger, when the build workflow succeeded, see https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
on:
  workflow_run:
    workflows: 
      - build_firmware
      - build_simhub_plugin
    types:
      - completed
      
      
      
# This is the list of jobs that will be run concurrently.
# Since we use a build matrix, the actual number of jobs
# started depends on how many configurations the matrix
# will produce.

# https://docs.github.com/de/actions/using-workflows/storing-workflow-data-as-artifacts

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for build_simhub_plugin
        uses: actions/download-artifact@v2
        with:
          name: simhub_plugin
          
          
          
      - name: Download math result for build_firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware_esp32
          
      - name: Print the final result
        shell: bash
        run: |
          echo The result is good
